language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t itanyusha/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true itanyusha/react-test npm test

after_success:
  - docker build -t itanyusha/multi-client ./client
  - docker build -t itanyusha/multi-nginx ./nginx
  - docker build -t itanyusha/multi-server ./server
  - docker build -t itanyusha/multi-worker ./worker

  # Log in to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker build itanyusha/multi-client
  - docker build itanyusha/multi-nginx
  - docker build itanyusha/multi-server
  - docker build itanyusha/multi-worker
